/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KarnatakaLandAudit } from './KarnatakaLandAudit.js';
export * as factories from './factories/index.js';
export { KarnatakaLandAudit__factory } from './factories/KarnatakaLandAudit__factory.js';