/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace KarnatakaLandAudit {
      
    export type ParcelEventStruct = {eventId: BigNumberish, parcelKey: BytesLike, documentHash: BytesLike, eventType: string, recordType: string, metadataURI: string, anchoredAt: BigNumberish, anchoredBy: AddressLike}

    export type ParcelEventStructOutput = [eventId: bigint, parcelKey: string, documentHash: string, eventType: string, recordType: string, metadataURI: string, anchoredAt: bigint, anchoredBy: string] & {eventId: bigint, parcelKey: string, documentHash: string, eventType: string, recordType: string, metadataURI: string, anchoredAt: bigint, anchoredBy: string }
  
    }

  export interface KarnatakaLandAuditInterface extends Interface {
    getFunction(nameOrSignature: "anchorParcelEvent" | "authorizeAnchorer" | "authorizedAnchorers" | "getParcelEventCount" | "getParcelEvents" | "owner" | "totalEvents" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AnchorerAuthorizationUpdated" | "OwnershipTransferred" | "ParcelAuditAnchored"): EventFragment;

    encodeFunctionData(functionFragment: 'anchorParcelEvent', values: [BytesLike, BytesLike, string, string, string]): string;
encodeFunctionData(functionFragment: 'authorizeAnchorer', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'authorizedAnchorers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getParcelEventCount', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getParcelEvents', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalEvents', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'anchorParcelEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizeAnchorer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedAnchorers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getParcelEventCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getParcelEvents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEvents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace AnchorerAuthorizationUpdatedEvent {
      export type InputTuple = [anchorer: AddressLike, allowed: boolean];
      export type OutputTuple = [anchorer: string, allowed: boolean];
      export interface OutputObject {anchorer: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ParcelAuditAnchoredEvent {
      export type InputTuple = [eventId: BigNumberish, parcelKey: BytesLike, documentHash: BytesLike, eventType: string, recordType: string, metadataURI: string, anchoredBy: AddressLike];
      export type OutputTuple = [eventId: bigint, parcelKey: string, documentHash: string, eventType: string, recordType: string, metadataURI: string, anchoredBy: string];
      export interface OutputObject {eventId: bigint, parcelKey: string, documentHash: string, eventType: string, recordType: string, metadataURI: string, anchoredBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KarnatakaLandAudit extends BaseContract {
    
    connect(runner?: ContractRunner | null): KarnatakaLandAudit;
    waitForDeployment(): Promise<this>;

    interface: KarnatakaLandAuditInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    anchorParcelEvent: TypedContractMethod<
      [parcelKey: BytesLike, documentHash: BytesLike, eventType: string, recordType: string, metadataURI: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    authorizeAnchorer: TypedContractMethod<
      [anchorer: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    authorizedAnchorers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getParcelEventCount: TypedContractMethod<
      [parcelKey: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getParcelEvents: TypedContractMethod<
      [parcelKey: BytesLike, ],
      [KarnatakaLandAudit.ParcelEventStructOutput[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalEvents: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'anchorParcelEvent'): TypedContractMethod<
      [parcelKey: BytesLike, documentHash: BytesLike, eventType: string, recordType: string, metadataURI: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizeAnchorer'): TypedContractMethod<
      [anchorer: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizedAnchorers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getParcelEventCount'): TypedContractMethod<
      [parcelKey: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getParcelEvents'): TypedContractMethod<
      [parcelKey: BytesLike, ],
      [KarnatakaLandAudit.ParcelEventStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalEvents'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AnchorerAuthorizationUpdated'): TypedContractEvent<AnchorerAuthorizationUpdatedEvent.InputTuple, AnchorerAuthorizationUpdatedEvent.OutputTuple, AnchorerAuthorizationUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ParcelAuditAnchored'): TypedContractEvent<ParcelAuditAnchoredEvent.InputTuple, ParcelAuditAnchoredEvent.OutputTuple, ParcelAuditAnchoredEvent.OutputObject>;

    filters: {
      
      'AnchorerAuthorizationUpdated(address,bool)': TypedContractEvent<AnchorerAuthorizationUpdatedEvent.InputTuple, AnchorerAuthorizationUpdatedEvent.OutputTuple, AnchorerAuthorizationUpdatedEvent.OutputObject>;
      AnchorerAuthorizationUpdated: TypedContractEvent<AnchorerAuthorizationUpdatedEvent.InputTuple, AnchorerAuthorizationUpdatedEvent.OutputTuple, AnchorerAuthorizationUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ParcelAuditAnchored(uint256,bytes32,bytes32,string,string,string,address)': TypedContractEvent<ParcelAuditAnchoredEvent.InputTuple, ParcelAuditAnchoredEvent.OutputTuple, ParcelAuditAnchoredEvent.OutputObject>;
      ParcelAuditAnchored: TypedContractEvent<ParcelAuditAnchoredEvent.InputTuple, ParcelAuditAnchoredEvent.OutputTuple, ParcelAuditAnchoredEvent.OutputObject>;
    
    };
  }